# Generated by Django 3.1.1 on 2020-12-06 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='developer',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
