# Generated by Django 3.1.1 on 2020-12-08 23:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='play_if_you_like',
            field=tinymce.models.HTMLField(default='default'),
            preserve_default=False,
        ),
    ]
