# Generated by Django 3.1.1 on 2020-12-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_review_play_if_you_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(default='', max_length=100)),
                ('email_of_user', models.EmailField(max_length=254)),
                ('title', models.CharField(db_index=True, default='', max_length=100)),
                ('external_link', models.URLField(blank=True, help_text='Where else can I read about the film? e.g. wikipedia, or IMDB page')),
                ('synopsis', models.TextField(help_text='Give a brief description of the game, in your own words.')),
            ],
        ),
    ]
