# Generated by Django 3.1.1 on 2020-12-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userrecommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecommendation',
            old_name='email_of_user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userrecommendation',
            old_name='external_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='userrecommendation',
            old_name='name_of_user',
            new_name='name',
        ),
    ]
